### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by cfelletter** [usbr/Process-MTOM-R#9]
@rabutler-usbr do you have any thoughts on output image size and format to use as our standard? I've been making pdfs width=9, height=6 which just standard ggplot font sizes. This seems to look pretty nice but as @sbaker2423 and @eaalexander have discussed this forces you to screen shot the plot if you need to put in a presentation or paper which is tacky. We could output a additional jpeg or png but I haven't got them to look as nice (perhaps because I'm not setting the graphics parameters to the equivalent of a 6x9 pdf?)

**Comment by rabutler-usbr** [comment]
I'd recommend using Adobe to convert the pdfs to pngs instead of taking a screen shot. That's still a bit of an annoying step, but it's what I often do. 

Otherwise, `ggsave("fig1.png", width = 9, height = 6, dpi = 600)` will create decently high res png file. If you are using in a formal report, I think you'll want to play with the height/width so that it fits better in the doc.

**Comment by cfelletter** [comment]
I went the ggsave route with users getting the option for width, height and device.

**Comment by eaalexander** [comment]
ggood call
